
package org.rasea.agent.seam.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccessControl", targetNamespace = "http://rasea.org/ws/AccessControl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccessControl {


    /**
     * 
     * @param assignedRoles
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.AssignedRolesResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "assignedRolesResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "assignedRolesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AssignedRolesResponse assignedRoles(
        @WebParam(name = "assignedRoles", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "assignedRoles")
        AssignedRoles assignedRoles,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param assignedUsers
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.AssignedUsersResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "assignedUsersResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "assignedUsersResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AssignedUsersResponse assignedUsers(
        @WebParam(name = "assignedUsers", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "assignedUsers")
        AssignedUsers assignedUsers,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns boolean
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "authenticated", targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.AuthenticateResponse")
    public boolean authenticate(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param changePassword
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.ChangePasswordResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "changePasswordResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "changePasswordResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ChangePasswordResponse changePassword(
        @WebParam(name = "changePassword", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "changePassword")
        ChangePassword changePassword,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param listRoles
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.ListRolesResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "listRolesResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "listRolesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListRolesResponse listRoles(
        @WebParam(name = "listRoles", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "listRoles")
        ListRoles listRoles,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param listUsers
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.ListUsersResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "listUsersResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "listUsersResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListUsersResponse listUsers(
        @WebParam(name = "listUsers", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "listUsers")
        ListUsers listUsers,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param username
     * @return
     *     returns boolean
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "requested", targetNamespace = "")
    @RequestWrapper(localName = "requestConfirmationCode", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.RequestConfirmationCode")
    @ResponseWrapper(localName = "requestConfirmationCodeResponse", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.RequestConfirmationCodeResponse")
    public boolean requestConfirmationCode(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param username
     * @param confirmationCode
     * @return
     *     returns boolean
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "reseted", targetNamespace = "")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://rasea.org/ws/AccessControl", className = "org.rasea.agent.seam.proxy.ResetPasswordResponse")
    public boolean resetPassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "confirmationCode", targetNamespace = "")
        String confirmationCode)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param raseaServiceHeader
     * @param roleDetail
     * @return
     *     returns org.rasea.agent.seam.proxy.RoleDetailResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "roleDetailResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleDetailResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RoleDetailResponse roleDetail(
        @WebParam(name = "roleDetail", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleDetail")
        RoleDetail roleDetail,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param roleEnabled
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.RoleEnabledResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "roleEnabledResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleEnabledResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RoleEnabledResponse roleEnabled(
        @WebParam(name = "roleEnabled", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleEnabled")
        RoleEnabled roleEnabled,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param raseaServiceHeader
     * @param roleOperationsOnResource
     * @return
     *     returns org.rasea.agent.seam.proxy.RoleOperationsOnResourceResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "roleOperationsOnResourceResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleOperationsOnResourceResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RoleOperationsOnResourceResponse roleOperationsOnResource(
        @WebParam(name = "roleOperationsOnResource", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "roleOperationsOnResource")
        RoleOperationsOnResource roleOperationsOnResource,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param rolePermissions
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.RolePermissionsResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "rolePermissionsResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "rolePermissionsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RolePermissionsResponse rolePermissions(
        @WebParam(name = "rolePermissions", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "rolePermissions")
        RolePermissions rolePermissions,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param unassignedRoles
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.UnassignedRolesResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "unassignedRolesResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "unassignedRolesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UnassignedRolesResponse unassignedRoles(
        @WebParam(name = "unassignedRoles", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "unassignedRoles")
        UnassignedRoles unassignedRoles,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param userDetail
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.UserDetailResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "userDetailResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userDetailResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserDetailResponse userDetail(
        @WebParam(name = "userDetail", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userDetail")
        UserDetail userDetail,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param userEnabled
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.UserEnabledResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "userEnabledResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userEnabledResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserEnabledResponse userEnabled(
        @WebParam(name = "userEnabled", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userEnabled")
        UserEnabled userEnabled,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param userOperationsOnResource
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.UserOperationsOnResourceResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "userOperationsOnResourceResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userOperationsOnResourceResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserOperationsOnResourceResponse userOperationsOnResource(
        @WebParam(name = "userOperationsOnResource", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userOperationsOnResource")
        UserOperationsOnResource userOperationsOnResource,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param userPermissions
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.UserPermissionsResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "userPermissionsResponse", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userPermissionsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserPermissionsResponse userPermissions(
        @WebParam(name = "userPermissions", targetNamespace = "http://rasea.org/ws/AccessControl", partName = "userPermissions")
        UserPermissions userPermissions,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/AccessControl", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

}
