
package org.rasea.agent.seam.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccessControlService", targetNamespace = "http://rasea.org/ws/AccessControl", wsdlLocation = "http://localhost:8080/rasea/services/AccessControl?wsdl")
public class AccessControlService
    extends Service
{

    private final static URL ACCESSCONTROLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.rasea.agent.seam.proxy.AccessControlService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.rasea.agent.seam.proxy.AccessControlService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/rasea/services/AccessControl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/rasea/services/AccessControl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCESSCONTROLSERVICE_WSDL_LOCATION = url;
    }

    public AccessControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessControlService() {
        super(ACCESSCONTROLSERVICE_WSDL_LOCATION, new QName("http://rasea.org/ws/AccessControl", "AccessControlService"));
    }

    /**
     * 
     * @return
     *     returns AccessControl
     */
    @WebEndpoint(name = "AccessControlPort")
    public AccessControl getAccessControlPort() {
        return super.getPort(new QName("http://rasea.org/ws/AccessControl", "AccessControlPort"), AccessControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccessControl
     */
    @WebEndpoint(name = "AccessControlPort")
    public AccessControl getAccessControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rasea.org/ws/AccessControl", "AccessControlPort"), AccessControl.class, features);
    }

}
