
package org.rasea.agent.seam.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Management", targetNamespace = "http://rasea.org/ws/Management")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Management {


    /**
     * 
     * @param addRole
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.AddRoleResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "addRoleResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "addRoleResponse")
    public AddRoleResponse addRole(
        @WebParam(name = "addRole", targetNamespace = "http://rasea.org/ws/Management", partName = "addRole")
        AddRole addRole,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param addUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.AddUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "addUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "addUserResponse")
    public AddUserResponse addUser(
        @WebParam(name = "addUser", targetNamespace = "http://rasea.org/ws/Management", partName = "addUser")
        AddUser addUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param assignUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.AssignUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "assignUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "assignUserResponse")
    public AssignUserResponse assignUser(
        @WebParam(name = "assignUser", targetNamespace = "http://rasea.org/ws/Management", partName = "assignUser")
        AssignUser assignUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param deassignUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.DeassignUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "deassignUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "deassignUserResponse")
    public DeassignUserResponse deassignUser(
        @WebParam(name = "deassignUser", targetNamespace = "http://rasea.org/ws/Management", partName = "deassignUser")
        DeassignUser deassignUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param deleteRole
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.DeleteRoleResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "deleteRoleResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "deleteRoleResponse")
    public DeleteRoleResponse deleteRole(
        @WebParam(name = "deleteRole", targetNamespace = "http://rasea.org/ws/Management", partName = "deleteRole")
        DeleteRole deleteRole,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param deleteUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.DeleteUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "deleteUserResponse")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "deleteUser", targetNamespace = "http://rasea.org/ws/Management", partName = "deleteUser")
        DeleteUser deleteUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param disableRole
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.DisableRoleResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "disableRoleResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "disableRoleResponse")
    public DisableRoleResponse disableRole(
        @WebParam(name = "disableRole", targetNamespace = "http://rasea.org/ws/Management", partName = "disableRole")
        DisableRole disableRole,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param disableUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.DisableUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "disableUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "disableUserResponse")
    public DisableUserResponse disableUser(
        @WebParam(name = "disableUser", targetNamespace = "http://rasea.org/ws/Management", partName = "disableUser")
        DisableUser disableUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param enableRole
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.EnableRoleResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "enableRoleResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "enableRoleResponse")
    public EnableRoleResponse enableRole(
        @WebParam(name = "enableRole", targetNamespace = "http://rasea.org/ws/Management", partName = "enableRole")
        EnableRole enableRole,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param enableUser
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.EnableUserResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "enableUserResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "enableUserResponse")
    public EnableUserResponse enableUser(
        @WebParam(name = "enableUser", targetNamespace = "http://rasea.org/ws/Management", partName = "enableUser")
        EnableUser enableUser,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param grantPermission
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.GrantPermissionResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "grantPermissionResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "grantPermissionResponse")
    public GrantPermissionResponse grantPermission(
        @WebParam(name = "grantPermission", targetNamespace = "http://rasea.org/ws/Management", partName = "grantPermission")
        GrantPermission grantPermission,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

    /**
     * 
     * @param revokePermission
     * @param raseaServiceHeader
     * @return
     *     returns org.rasea.agent.seam.proxy.RevokePermissionResponse
     * @throws RaseaServiceException
     */
    @WebMethod
    @WebResult(name = "revokePermissionResponse", targetNamespace = "http://rasea.org/ws/Management", partName = "revokePermissionResponse")
    public RevokePermissionResponse revokePermission(
        @WebParam(name = "revokePermission", targetNamespace = "http://rasea.org/ws/Management", partName = "revokePermission")
        RevokePermission revokePermission,
        @WebParam(name = "raseaServiceHeader", targetNamespace = "http://rasea.org/ws/Management", header = true, partName = "raseaServiceHeader")
        RaseaServiceHeader raseaServiceHeader)
        throws RaseaServiceException
    ;

}
