
package org.rasea.agent.seam.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RaseaServiceException", targetNamespace = "http://rasea.org/ws/Maintenance")
public class RaseaServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RaseaServiceFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RaseaServiceException(String message, RaseaServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RaseaServiceException(String message, RaseaServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.rasea.agent.seam.proxy.RaseaServiceFault
     */
    public RaseaServiceFault getFaultInfo() {
        return faultInfo;
    }

}
